version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - cdk --version
      - python --version
      
  build:
    commands:
      - echo "Synthesizing CDK app..."
      - cdk synth
      - echo "Deploying CDK stacks..."
      - cdk deploy --all --require-approval never

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
